version: '3.7'

services:
  vue-app:
    container_name: vue-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - jftse-db


  jftse-db:
    build: ./db
    container_name: jftse-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
#     Set max_allowed_packet to 64MB
    command: --max_allowed_packet=67108864
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
      - MYSQL_ROOT_USER=${DB_PASSWORD}
      - TZ=Europe/London
